services:
  db:
    image: postgres:latest
    container_name: db-realworld-back
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-realworld-back-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:latest
    container_name: minio-realworld-back
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address :9001
    ports:
      - '9001:9001'
      - '9000:9000'
    volumes:
      - minio-realworld-back-volume:/data
  app:
    build:
      context: .
    container_name: app-realworld-back
    depends_on:
      - minio
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

volumes:
  db-realworld-back-volume:
    name: db-realworld-back-volume
  minio-realworld-back-volume:
    name: minio-realworld-back-volume

