spring:
  application:
    name: realworld-back
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 2
    refresh: 30

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}